# Generated by Django 5.1.3 on 2024-11-16 01:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Campus')),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campi',
            },
        ),
        migrations.CreateModel(
            name='FormaIngresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Forma de inbgresso')),
            ],
            options={
                'verbose_name': 'Ingresso',
                'verbose_name_plural': 'formaIngresso',
            },
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome Da Situacao')),
            ],
            options={
                'verbose_name': 'Situação',
                'verbose_name_plural': 'Situações',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Curso')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='piloto.campus', verbose_name='Campus')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCompleto', models.CharField(max_length=500, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('matricula', models.CharField(editable=False, max_length=10, unique=True, verbose_name='Matricula')),
                ('dataNascimento', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='alunos_fotos/', verbose_name='Foto Aluno')),
                ('dataCadastro', models.DateField(default=datetime.date.today, verbose_name='data de cadastro')),
                ('dataUpdate', models.DateTimeField(auto_now=True, verbose_name='Ultima atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Aluno vinculado na instituição?')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='piloto.curso', verbose_name='Curso')),
                ('formaIngresso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='piloto.formaingresso', verbose_name='Forma de Ingresso')),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='piloto.situacao', verbose_name='Situação')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
    ]
