# Generated by Django 5.1.3 on 2024-12-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piloto', '0002_alter_aluno_datanascimento_alter_formaingresso_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='situacao',
        ),
        migrations.AddField(
            model_name='situacao',
            name='estaNaInstituicao',
            field=models.BooleanField(default=True),
        ),
    ]
