# Generated by Django 5.1.3 on 2024-12-02 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piloto', '0003_remove_aluno_situacao_situacao_estanainstituicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='situacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='piloto.situacao'),
        ),
    ]
