# Generated by Django 5.1.3 on 2024-12-04 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piloto', '0004_aluno_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='situacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='piloto.situacao', verbose_name='Situacao'),
        ),
        migrations.AlterField(
            model_name='situacao',
            name='estaNaInstituicao',
            field=models.BooleanField(default=True, verbose_name='ativo na instituicao'),
        ),
    ]
